title: "Vector & Verse"
description: "Personal blog exploring artificial intelligence and life, as I know it."
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
url: "https://kirankannar.github.io"
baseurl: ""

navigation:
  - label: "Main"
    data: "navigation.yml"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-archives

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      show_meta: true
      show_tags: true
      author_profile: true # Add this if you want the author sidebar

masthead_title: "Vector & Verse"
author:
  name: "Kiran Kannar"
  avatar: "img/dp.jpg"
  bio: "I blog about ML, NLP, and living in SF."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/kannarkk/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/kirankannar"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/kannarkk"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:kiran.kannar@gmail.com"

timezone: America/San_Francisco

# Additional site settings
night_mode: "manual"
locale: "en-US"
search: true
search_full_content: true
search_provider: lunr

# Comments settings
comments:
  provider: "disqus"
  disqus:
    shortname: "kannars-ml-blog"

# Analytics settings
# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "UA-XXXXXXXXX-X"
#     anonymize_ip: false

# Social sharing
social:
  type: Person
  links:
    - "https://twitter.com/kannarkk"
    - "https://github.com/kannarkk"

# Reading time estimates
words_per_minute: 200

# Pagination
# paginate: 5
# paginate_path: /page:num/

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    tag: archive
  permalinks:
    tag: /tag/:name/
    category: /category/:name/


exclude: ["README.md", "Gemfile", "Gemfile.lock"]
